##
# UAVLAB Documentation PDF makefile
#

# end

pth:
	pandoc UAVLAB-serial-pth-documentation.org -o UAVLAB-serial-pth-documentation.pdf --template eisvogel --listings

i2c:
	pandoc UAVLAB-i2c-5hole-probe-documentation.org -o UAVLAB-i2c-5hole-probe-documentation.pdf --template eisvogel --listings

anem:
	pandoc UAVLAB-sonic-anemometer-documentation.org -o UAVLAB-sonic-anemometer-documentation.pdf --template eisvogel --listings
